server:
  port: 8088



spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: rain@123#
    sentinel:
      master:
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
